[package]
name = "logging"
version = "0.1.0"
authors = ["Elmar Athmer <elmar.athmer@rewe-digital.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapp = { path = "../core" }
log = "0.4.8"
